version: "3.7"

services:
  front:
    container_name: front
    build:
      context: front/
    ports:
      - "81:80"
  backend:
    container_name: backend
    build:
      context: api/
    ports:
      - "8000:8000"
