# Generated by Django 3.1.1 on 2020-09-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated']},
        ),
    ]
